# Generated by Django 4.0.4 on 2022-05-09 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0005_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='captaioon',
            new_name='caption',
        ),
    ]
