# Generated by Django 4.0.4 on 2022-05-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0006_rename_captaioon_video_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='new_field',
            field=models.CharField(default='["что происходит малыш тебе уже третира словят на драке я знаю пора бы же научиться  я не могу тебе понять папа мог я тоже по нему скучаю ты должен думать о будущемскорее чем кажетсяпойдем ка лучшее отсюда тоздесь без истерикпп гараж ты знал как закрыть холодильник у нас одинаковые шрам вотздесь и на тебе папина часы воды тытыя тайная информации копутешествия по времени существут этот мир дашвир все уше изменилось но вы загониме ина братнат в бутылкахсти со всех сил постарайс ни выробится о перегрузке"]', max_length=140),
        ),
    ]
