# Generated by Django 4.0.4 on 2022-05-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0007_video_new_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='new_field',
            field=models.CharField(default='[" сарики"]', max_length=140),
        ),
    ]
