# Generated by Django 4.0.4 on 2022-05-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0010_alter_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
