# Generated by Django 4.0.4 on 2022-05-20 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0013_video_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='slug',
        ),
    ]
